spring.application.name=bloom-username-checker

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/bloomdb
spring.datasource.username=root
spring.datasource.password=143@Rubun

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# This tells Spring Boot to run data.sql after Hibernate creates the tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
